openapi: '3.0.1'
info:
  title: Cadastro de Despesas
  description: >
    O Cadastro de Despesas é um serviço que gerencia as despesas. Cada despesa possui uma descrição, um valor, uma data, uma imagem e um documento opcional.
  version: '0.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'
paths:
  /despesas:
    get:
      summary: Acessar todas as despesas
      responses:
        '200':
          description: Lista de despesas obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Despesa'

    post:
      summary: Criar uma nova despesa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: O ID do usuário associado à despesa.
                  example: 1
                descricao:
                  type: string
                  description: A descrição da despesa.
                  example: "Compra de materiais"
                value:
                  type: number
                  format: float
                  description: O valor da despesa.
                  example: 150.75
                data:
                  type: string
                  format: date
                  description: A data da despesa.
                  example: "2024-10-20"
                imagem:
                  type: string
                  description: O caminho da imagem relacionada à despesa.
                  example: "imagens/exemplo.jpg"
                documento:
                  type: string
                  description: O caminho do documento relacionado à despesa.
                  example: "documentos/exemplo.pdf"
      responses:
        '201':
          description: Despesa criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: O URI do novo recurso criado.
        '400':
          description: Requisição inválida

  /despesas/{id}:
    get:
      summary: Obter uma despesa específica
      parameters:
        - name: id
          in: path
          required: true
          description: ID da despesa
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da despesa obtidos com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Despesa'
        '404':
          description: Despesa não encontrada

    put:
      summary: Atualizar uma despesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID da despesa
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
                  description: A descrição da despesa.
                  example: "Compra de equipamentos"
                value:
                  type: number
                  format: float
                  description: O novo valor da despesa.
                  example: 200.00
                data:
                  type: string
                  format: date
                  description: A nova data da despesa.
                  example: "2024-10-21"
                imagem:
                  type: string
                  description: O caminho da nova imagem relacionada à despesa.
                  example: "imagens/nova_exemplo.jpg"
                documento:
                  type: string
                  description: O caminho do novo documento relacionado à despesa.
                  example: "documentos/nova_exemplo.pdf"
      responses:
        '200':
          description: Despesa atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Despesa'
        '400':
          description: dados em formato errado)
        '404':
          description: Despesa não encontrada

    delete:
      summary: Deletar uma despesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID da despesa
          schema:
            type: integer
      responses:
        '204':
          description: Despesa deletada com sucesso
        '404':
          description: Despesa não encontrada

components:
  schemas:
    Despesa:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        descricao:
          type: string
        value:
          type: number
          format: float
        data:
          type: string
          format: date
        imagem:
          type: string
          description: O caminho da imagem relacionada à despesa.
        documento:
          type: string
          description: O caminho do documento relacionado à despesa.
